# 아래 설정들은 운영환경, 테스트환경, 개발환경에서 공통으로 사용된다.
spring:
  profiles:
    active: dev # 기본적으로는 application-dev.yml 이 로딩된다는 의미, activeProfiles 에 의해서 바뀔 수 있음
  threads:
    virtual:
      enabled: true # 자바 21, 스프링 3.20 이상부터 사용가능, 요청처리에 사용되는 쓰레드가 Non-Blocking 방식으로 작동하도록
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100 # Lazy 로딩이 될 때 한번에 DB에서 가져오는 데이터의 수
        format_sql: true # SQL 로그를 보기 좋게 포맷팅
        highlight_sql: true # SQL 로그에 하이라이트
        use_sql_comments: true # SQL 로그에 코멘트
logging:
  level:
    com.ll.sb231130restapi: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
custom:
  site:
    name: rest2023
    baseUrl: "http://localhost:${server.port}"